### ISSUE TITLE
[Bug] Récupération des infos d'un assessment : Cannot return null for non-nullable field Assessment.id

### ISSUE THREAD

**Issue by vvandenschrieck** [TLCA-project/tlca-backend#2]
Version : develop - commit [593b56c](https://github.com/TLCA-project/tlca-backend/commit/593b56ca1f286b763fc3d4d63670b64bce03ef1f)

Depuis la liste des assessments d'un cours, lorsqu'on clique sur un assessment particulier pour afficher la page le détaillant, la page ne s'affiche pas et l'erreur "Cannot return null for non-nullable field Assessment.id." apparaît dans le popup. 

<img width="1161" alt="Capture d’écran 2022-08-12 à 10 47 33" src="https://user-images.githubusercontent.com/1985444/184319327-3a3cb917-e951-4abe-a90d-a340fe016033.png">

La requête GraphQL "GetCourseAssessment" avec les paramètres "courseCode" et "assessmentId" corrects renvoie la réponse suivante : 

```
{
    "errors": [
        {
            "message": "Cannot return null for non-nullable field Assessment.id.",
            "locations": [
                {
                    "line": 9,
                    "column": 5
                }
            ],
            "path": [
                "assessment",
                "id"
            ],
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR",
                "exception": {
                    "stacktrace": [
                        "Error: Cannot return null for non-nullable field Assessment.id.",
                        "    at completeValue (/tlca-backend/node_modules/graphql/execution/execute.js:594:13)",
                        "    at executeField (/tlca-backend/node_modules/graphql/execution/execute.js:489:19)",
                        "    at executeFields (/tlca-backend/node_modules/graphql/execution/execute.js:413:20)",
                        "    at completeObjectValue (/tlca-backend/node_modules/graphql/execution/execute.js:914:10)",
                        "    at completeValue (/tlca-backend/node_modules/graphql/execution/execute.js:635:12)",
                        "    at /tlca-backend/node_modules/graphql/execution/execute.js:486:9",
                        "    at runMicrotasks (<anonymous>)",
                        "    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
                        "    at runNextTicks (node:internal/process/task_queues:65:3)",
                        "    at processImmediate (node:internal/timers:437:9)"
                    ]
                }
            }
        }
    ],
    "data": {
        "course": {
            "code": "T202",
            "name": "Cours test",
            "__typename": "Course"
        },
        "assessment": null
    }
}
 
```

**Comment by combefis** [comment]
Merci @vvandenschrieck  !

Le problème a été identifié, le resolver spécifique au champ "id" pour les "assessments" n'était pas défini.

Le bug a été corrigé par le commit ee34c06064f2827ed9391d51d20474140fbaf7fb qui a été intégré dans la branche develop et également appliqué à la release 1.0 (v1.0.1).
